engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 34
  pep8:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
   - "**.py"
exclude_paths:
  - "MuseParse/tests/**"
